# 网易新闻


[base]
#爬虫名字
name = "163news"

#是否启用
enable=true

#并发数
threadNum=30

#爬虫入口 每次启动必爬
index=[http://news.163.com/,http://auto.163.com/,http://tech.163.com/]

#允许爬取网站的域名
domain = [news.163.com,tech.163.com,auto.163.com]


#抓取的目标规则 goquery
[target]



