# 网易新闻


#爬虫名字
name = "腾讯新闻"

#是否启用
enable=true

#并发数
threadNum=30

#爬虫入口 每次启动必爬
index=["http://news.qq.com/"]

#允许爬取网站的域名
domain = ["news.qq.com"]

#抓取的目标规则 goquery
[target]
  [target.title]
  selector = "selector"
  regexp = "regexp"



